Token Type: Keyword
Token Value: class
Token Type: Identifier
Token Value: Person
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: first
Token Type: Delimiter
Token Value: newline
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: last
Token Type: Delimiter
Token Value: newline
Token Type: Identifier
Token Value: void
Token Type: FunctionCall
Token Value: setFirst()
Token Type: Identifier
Token Value: first
Token Type: Identifier
Token Value: println
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: this.first
Token Type: Identifier
Token Value: first
Token Type: StringLiteral
Token Value: "${this.first} is becoming ${first}"
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: this.first
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: first
Token Type: Delimiter
Token Value: newline
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
