Token Type: Keyword
Token Value: class
Token Type: TypeAnnotation
Token Value: Sort
Token Type: Keyword
Token Value: def
Token Type: FunctionCall
Token Value: quickSort()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: left
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: right
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: left
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: right
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: pivotIndex
Token Type: Assignment
Token Value: =
Token Type: FunctionCall
Token Value: partition()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: left
Token Type: Identifier
Token Value: right
Token Type: FunctionCall
Token Value: quickSort()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: left
Token Type: Identifier
Token Value: pivotIndex
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: FunctionCall
Token Value: quickSort()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: pivotIndex
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Identifier
Token Value: right
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Identifier
Token Value: def
Token Type: FunctionCall
Token Value: partition()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: left
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: right
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: pivot
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: right
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: left
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: j
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: left
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: j
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: right
Token Type: Delimiter
Token Value: ;
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: j
Token Type: Keyword
Token Value: if
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: LessOrEqual
Token Value: <=
Token Type: Identifier
Token Value: pivot
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: i
Token Type: FunctionCall
Token Value: swap()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: i
Token Type: Identifier
Token Value: j
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: FunctionCall
Token Value: swap()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: i
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Identifier
Token Value: right
Token Type: Keyword
Token Value: return
Token Type: Identifier
Token Value: i
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: def
Token Type: FunctionCall
Token Value: bubbleSort()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: n
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: array.length
Token Type: Delimiter
Token Value: new line
Token Type: TypeAnnotation
Token Value: boolean
Token Type: Identifier
Token Value: swapped
Token Type: Delimiter
Token Value: new line
Token Type: Identifier
Token Value: swapped
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: false
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: n
Token Type: Delimiter
Token Value: ;
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: i
Token Type: Keyword
Token Value: if
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: GreaterThan
Token Value: >
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: FunctionCall
Token Value: swap()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: i
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: Identifier
Token Value: i
Token Type: Identifier
Token Value: swapped
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: true
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Identifier
Token Value: n
Token Type: Identifier
Token Value: n
Token Type: PostfixDecrement
Token Value: --
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: while
Token Type: Parentheses
Token Value: ()
Token Type: Identifier
Token Value: swapped
Token Type: Braces
Token Value: {}
Token Type: Identifier
Token Value: def
Token Type: FunctionCall
Token Value: interpolationSort()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: n
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: array.length
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: n
Token Type: Delimiter
Token Value: ;
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: i
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: key
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: j
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: i
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: while
Token Type: Parentheses
Token Value: ()
Token Type: Identifier
Token Value: j
Token Type: GreaterOrEqual
Token Value: >=
Token Type: NumberLiteral
Token Value: 0
Token Type: And
Token Value: &&
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: GreaterThan
Token Value: >
Token Type: Identifier
Token Value: key
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: Identifier
Token Value: j
Token Type: Identifier
Token Value: j
Token Type: PostfixDecrement
Token Value: --
Token Type: Braces
Token Value: {}
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: key
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: def
Token Type: FunctionCall
Token Value: heapSort()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: n
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: array.length
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: n
Token Type: Slash
Token Value: /
Token Type: NumberLiteral
Token Value: 2
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: GreaterOrEqual
Token Value: >=
Token Type: NumberLiteral
Token Value: 0
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: Identifier
Token Value: i
Token Type: PostfixDecrement
Token Value: --
Token Type: FunctionCall
Token Value: heapify()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: n
Token Type: Identifier
Token Value: i
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: n
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: GreaterThan
Token Value: >
Token Type: NumberLiteral
Token Value: 0
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: Identifier
Token Value: i
Token Type: PostfixDecrement
Token Value: --
Token Type: FunctionCall
Token Value: swap()
Token Type: Identifier
Token Value: array
Token Type: NumberLiteral
Token Value: 0
Token Type: Identifier
Token Value: i
Token Type: FunctionCall
Token Value: heapify()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: i
Token Type: NumberLiteral
Token Value: 0
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Identifier
Token Value: def
Token Type: FunctionCall
Token Value: heapify()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: n
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: largest
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: i
Token Type: Delimiter
Token Value: new line
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: left
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 2
Token Type: Star
Token Value: *
Token Type: Identifier
Token Value: i
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: new line
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: right
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 2
Token Type: Star
Token Value: *
Token Type: Identifier
Token Value: i
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 2
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: left
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: n
Token Type: And
Token Value: &&
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: left
Token Type: GreaterThan
Token Value: >
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: largest
Token Type: Identifier
Token Value: largest
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: left
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: right
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: n
Token Type: And
Token Value: &&
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: right
Token Type: GreaterThan
Token Value: >
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: largest
Token Type: Identifier
Token Value: largest
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: right
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: largest
Token Type: NotEqual
Token Value: !=
Token Type: Identifier
Token Value: i
Token Type: FunctionCall
Token Value: swap()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: i
Token Type: Identifier
Token Value: largest
Token Type: FunctionCall
Token Value: heapify()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: n
Token Type: Identifier
Token Value: largest
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: def
Token Type: FunctionCall
Token Value: selectionSort()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: n
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: array.length
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 0
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: n
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: ;
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: i
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: minIndex
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: i
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: j
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: i
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: j
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: n
Token Type: Delimiter
Token Value: ;
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: j
Token Type: Keyword
Token Value: if
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: LessThan
Token Value: <
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: minIndex
Token Type: Identifier
Token Value: minIndex
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: j
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: minIndex
Token Type: NotEqual
Token Value: !=
Token Type: Identifier
Token Value: i
Token Type: FunctionCall
Token Value: swap()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: i
Token Type: Identifier
Token Value: minIndex
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: TypeAnnotation
Token Value: void
Token Type: FunctionCall
Token Value: mergeSort()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: left
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: right
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: left
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: right
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: mid
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: left
Token Type: Plus
Token Value: +
Token Type: Parentheses
Token Value: ()
Token Type: Identifier
Token Value: right
Token Type: Minus
Token Value: -
Token Type: Identifier
Token Value: left
Token Type: Slash
Token Value: /
Token Type: NumberLiteral
Token Value: 2
Token Type: Delimiter
Token Value: new line
Token Type: FunctionCall
Token Value: mergeSort()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: left
Token Type: Identifier
Token Value: mid
Token Type: FunctionCall
Token Value: mergeSort()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: mid
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Identifier
Token Value: right
Token Type: FunctionCall
Token Value: merge()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: left
Token Type: Identifier
Token Value: mid
Token Type: Identifier
Token Value: right
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: TypeAnnotation
Token Value: void
Token Type: FunctionCall
Token Value: merge()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: left
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: mid
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: right
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: leftArray
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: Arrays.copyOfRange()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: left
Token Type: Identifier
Token Value: mid
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: rightArray
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: Arrays.copyOfRange()
Token Type: Identifier
Token Value: array
Token Type: Identifier
Token Value: mid
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: Identifier
Token Value: right
Token Type: Plus
Token Value: +
Token Type: NumberLiteral
Token Value: 1
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 0
Token Type: Identifier
Token Value: j
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 0
Token Type: Identifier
Token Value: k
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: left
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: while
Token Type: Parentheses
Token Value: ()
Token Type: Identifier
Token Value: i
Token Type: LessThan
Token Value: <
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: leftArray.length
Token Type: And
Token Value: &&
Token Type: Identifier
Token Value: j
Token Type: LessThan
Token Value: <
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: rightArray.length
Token Type: Keyword
Token Value: if
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: LessOrEqual
Token Value: <=
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: Brackets
Token Value: []
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: k
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: i
Token Type: Braces
Token Value: {}
Token Type: Brackets
Token Value: []
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: k
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: j
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: while
Token Type: Parentheses
Token Value: ()
Token Type: Identifier
Token Value: i
Token Type: LessThan
Token Value: <
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: leftArray.length
Token Type: Brackets
Token Value: []
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: k
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: i
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: while
Token Type: Parentheses
Token Value: ()
Token Type: Identifier
Token Value: j
Token Type: LessThan
Token Value: <
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: rightArray.length
Token Type: Brackets
Token Value: []
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: k
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: j
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: def
Token Type: FunctionCall
Token Value: swap()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: j
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: i
Token Type: NotEqual
Token Value: !=
Token Type: Identifier
Token Value: j
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: BitwiseXor
Token Value: ^
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: BitwiseXor
Token Value: ^
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: BitwiseXor
Token Value: ^
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: j
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: TypeAnnotation
Token Value: boolean
Token Type: FunctionCall
Token Value: isSortedAscending()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: LessThan
Token Value: <
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: array.length
Token Type: Delimiter
Token Value: ;
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: i
Token Type: Keyword
Token Value: if
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: GreaterThan
Token Value: >
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: Keyword
Token Value: return
Token Type: Identifier
Token Value: false
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: return
Token Type: Identifier
Token Value: true
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: def
Token Type: FunctionCall
Token Value: isSortedDescending()
Token Type: TypeAnnotation
Token Value: int[]
Token Type: Identifier
Token Value: array
Token Type: Keyword
Token Value: for
Token Type: TypeAnnotation
Token Value: int
Token Type: Identifier
Token Value: i
Token Type: Assignment
Token Value: =
Token Type: NumberLiteral
Token Value: 1
Token Type: Delimiter
Token Value: ;
Token Type: Identifier
Token Value: i
Token Type: LessThan
Token Value: <
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: array.length
Token Type: Delimiter
Token Value: ;
Token Type: PostfixIncrement
Token Value: ++
Token Type: Identifier
Token Value: i
Token Type: Keyword
Token Value: if
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: LessThan
Token Value: <
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: i
Token Type: Keyword
Token Value: return
Token Type: Identifier
Token Value: false
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: return
Token Type: Identifier
Token Value: true
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Identifier
Token Value: def
Token Type: FunctionCall
Token Value: findMinMax()
Token Type: Identifier
Token Value: arr
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: arr
Token Type: Equal
Token Value: ==
Token Type: Keyword
Token Value: null
Token Type: Or
Token Value: ||
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: arr.isEmpty()
Token Type: Keyword
Token Value: return
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: min
Token Type: Identifier
Token Value: null
Token Type: Identifier
Token Value: max
Token Type: Identifier
Token Value: null
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: min
Token Type: Assignment
Token Value: =
Token Type: SubscriptOperator
Token Value: collection[]
Token Type: NumberLiteral
Token Value: 0
Token Type: SubscriptOperator
Token Value: arr[0]
Token Type: Delimiter
Token Value: new line
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: max
Token Type: Assignment
Token Value: =
Token Type: SubscriptOperator
Token Value: collection[]
Token Type: NumberLiteral
Token Value: 0
Token Type: SubscriptOperator
Token Value: arr[0]
Token Type: Delimiter
Token Value: new line
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: arr.each
Token Type: Identifier
Token Value: num
Token Type: ClosureOperator
Token Value: ->
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: num
Token Type: LessThan
Token Value: <
Token Type: Identifier
Token Value: min
Token Type: Identifier
Token Value: min
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: num
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: if
Token Type: Identifier
Token Value: num
Token Type: GreaterThan
Token Value: >
Token Type: Identifier
Token Value: max
Token Type: Identifier
Token Value: max
Token Type: Assignment
Token Value: =
Token Type: Identifier
Token Value: num
Token Type: Delimiter
Token Value: new line
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
Token Type: Keyword
Token Value: return
Token Type: Brackets
Token Value: []
Token Type: Identifier
Token Value: min
Token Type: Identifier
Token Value: min
Token Type: Identifier
Token Value: max
Token Type: Identifier
Token Value: max
Token Type: Braces
Token Value: {}
Token Type: TypeAnnotation
Token Value: void
Token Type: FunctionCall
Token Value: main()
Token Type: TypeAnnotation
Token Value: String[]
Token Type: Identifier
Token Value: args
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: array
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: NumberLiteral
Token Value: 34
Token Type: NumberLiteral
Token Value: 7
Token Type: NumberLiteral
Token Value: 23
Token Type: NumberLiteral
Token Value: 32
Token Type: NumberLiteral
Token Value: 5
Token Type: NumberLiteral
Token Value: 62
Token Type: FunctionCall
Token Value: println()
Token Type: Identifier
Token Value: array
Token Type: StringLiteral
Token Value: "Original: ${array}"
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: quickSorted
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: array.clone()
Token Type: FunctionCall
Token Value: quickSort()
Token Type: Identifier
Token Value: quickSorted
Token Type: NumberLiteral
Token Value: 0
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: quickSorted.length
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: FunctionCall
Token Value: println()
Token Type: Identifier
Token Value: quickSorted
Token Type: StringLiteral
Token Value: "QuickSort: ${quickSorted}"
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: bubbleSorted
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: array.clone()
Token Type: FunctionCall
Token Value: bubbleSort()
Token Type: Identifier
Token Value: bubbleSorted
Token Type: FunctionCall
Token Value: println()
Token Type: Identifier
Token Value: bubbleSorted
Token Type: StringLiteral
Token Value: "BubbleSort: ${bubbleSorted}"
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: interpolationSorted
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: array.clone()
Token Type: FunctionCall
Token Value: interpolationSort()
Token Type: Identifier
Token Value: interpolationSorted
Token Type: FunctionCall
Token Value: println()
Token Type: Identifier
Token Value: interpolationSorted
Token Type: StringLiteral
Token Value: "InterpolationSort: ${interpolationSorted}"
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: heapSorted
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: array.clone()
Token Type: FunctionCall
Token Value: heapSort()
Token Type: Identifier
Token Value: heapSorted
Token Type: FunctionCall
Token Value: println()
Token Type: Identifier
Token Value: heapSorted
Token Type: StringLiteral
Token Value: "HeapSort: ${heapSorted}"
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: selectionSorted
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: array.clone()
Token Type: FunctionCall
Token Value: selectionSort()
Token Type: Identifier
Token Value: selectionSorted
Token Type: FunctionCall
Token Value: println()
Token Type: Identifier
Token Value: selectionSorted
Token Type: StringLiteral
Token Value: "SelectionSort: ${selectionSorted}"
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: mergeSorted
Token Type: Assignment
Token Value: =
Token Type: MemberAccess
Token Value: obj.member
Token Type: FunctionCall
Token Value: array.clone()
Token Type: FunctionCall
Token Value: mergeSort()
Token Type: Identifier
Token Value: mergeSorted
Token Type: NumberLiteral
Token Value: 0
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: mergeSorted.length
Token Type: Minus
Token Value: -
Token Type: NumberLiteral
Token Value: 1
Token Type: FunctionCall
Token Value: println()
Token Type: Identifier
Token Value: mergeSorted
Token Type: StringLiteral
Token Value: "MergeSort: ${mergeSorted}"
Token Type: FunctionCall
Token Value: println()
Token Type: FunctionCall
Token Value: isSortedAscending()
Token Type: Identifier
Token Value: array
Token Type: StringLiteral
Token Value: "Is Sorted Ascending: ${isSortedAscending(array)}"
Token Type: FunctionCall
Token Value: println()
Token Type: FunctionCall
Token Value: isSortedDescending()
Token Type: Identifier
Token Value: array
Token Type: StringLiteral
Token Value: "Is Sorted Descending: ${isSortedDescending(array)}"
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: array
Token Type: Assignment
Token Value: =
Token Type: Brackets
Token Value: []
Token Type: NumberLiteral
Token Value: 5
Token Type: NumberLiteral
Token Value: 2
Token Type: NumberLiteral
Token Value: 9
Token Type: NumberLiteral
Token Value: 1
Token Type: NumberLiteral
Token Value: 7
Token Type: Keyword
Token Value: def
Token Type: Identifier
Token Value: result
Token Type: Assignment
Token Value: =
Token Type: FunctionCall
Token Value: findMinMax()
Token Type: Identifier
Token Value: array
Token Type: Keyword
Token Value: println
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: result.min
Token Type: MemberAccess
Token Value: obj.member
Token Type: Identifier
Token Value: result.max
Token Type: Identifier
Token Value: "Min: ${result.min}, Max: ${result.max}"
Token Type: Braces
Token Value: {}
Token Type: Braces
Token Value: {}
