Keyword(class): 1
TypeAnnotation(Sort): 1
Keyword(def): 23
FunctionCall(quickSort()): 4
TypeAnnotation(int[]): 12
TypeAnnotation(int): 37
Keyword(if): 16
LessThan(<): 18
Assignment(=): 55
FunctionCall(partition()): 2
Minus(-): 13
Plus(+): 13
Braces({}): 47
Brackets([]): 42
Delimiter(new line): 29
Keyword(for): 9
Delimiter(;): 18
PostfixIncrement(++): 16
LessOrEqual(<=): 2
FunctionCall(swap()): 7
Keyword(return): 7
FunctionCall(bubbleSort()): 2
MemberAccess(obj.member): 24
TypeAnnotation(boolean): 2
GreaterThan(>): 7
PostfixDecrement(--): 4
Keyword(while): 5
FunctionCall(interpolationSort()): 2
GreaterOrEqual(>=): 2
And(&&): 4
FunctionCall(heapSort()): 2
Slash(/): 2
FunctionCall(heapify()): 4
Star(*): 2
NotEqual(!=): 3
FunctionCall(selectionSort()): 2
TypeAnnotation(void): 3
FunctionCall(mergeSort()): 4
Parentheses(()): 1
FunctionCall(merge()): 2
FunctionCall(Arrays.copyOfRange()): 2
BitwiseXor(^): 3
FunctionCall(isSortedAscending()): 2
FunctionCall(isSortedDescending()): 2
FunctionCall(findMinMax()): 2
Equal(==): 1
Keyword(null): 1
Or(||): 1
FunctionCall(arr.isEmpty()): 1
SubscriptOperator(collection[]): 2
SubscriptOperator(arr[0]): 2
ClosureOperator(->): 1
FunctionCall(main()): 1
TypeAnnotation(String[]): 1
FunctionCall(println()): 9
FunctionCall(array.clone()): 6
Keyword(println): 1
